sudo: false
language: node_js
node_js:
- 8
script:
- npm test
after_success:
- npm run report-coverage
env:
  matrix:
    secure: OLYVg+/5SEMI1mqfW40htQBwNOJYaBQ4o9OnVQGMP/wtUBLK7D+hw8YJAzhiEKOMZ+RMOBMpuKx3771d48DLvQiNfXw/tjGw9fhEh2zzCg9BCd0VwspbOSj4PMAntSN/2OqnB6BjzyW8AbW+lh43IlrxlkHgNRNuwJ/KMUIDwiuvC0TLrP5ISahdpAD5rqKyFrx/Fs/o4z2M7lpH1Dl/0iO/lY9yMbrO5xMtTy31tG7Q6jU5pJnqxIrAIyZUx3dEO59n0RxiB8tQU6Tnkuse29mOauN5ImsxNi8uMy1De30ZSSxhZ3aZoydiiZL2cV0Rb/pIBHN3Z+KV3J8FVjPCV0CqdbLgVsH8lw3Ycv3M4jY91FDqfQ4eyLtxvk9d9bojFtdppWs90Y3elgFeqzchMtDCL+pcnK3Y3SAJxGQu52dAnlqJNtzHfqBGwzbfmttXh6VrFTuxPmqPzNwgYJUyT0GUN4KbH315A7LvvewBeanelT1MUschQlEsartPRjm/gijqnlqZ/rRriUvDnG7luBOlwA8hVYtU5jYxORxGxVgE2UDsNh3xsBcLZ+PQEhjZKFCrr3sHIgXMv0juTxCGyVX4A9SH3OAPV2g0IFtHyjK1YwVtIMuWJJerN92NuUpt10KHg+jnKfoTg/1HoixMUJytqBgLYYaUgIpuStWfDMY=
deploy:
  provider: npm
  email: shasak.sync@gmail.com
  api_key:
    secure: Y23HjZt1n6J7WcEixdEZtmTSHC9qulLTMBORofFlru9eg2vDoD90+bPjhXXztokPi+HQso1cpeZ2IsA0XdmWjhfLDzZvYdd+GLyf4DBnIxtOhTwmLHgukImhZ6+crFiUxDxmuqmqbWaIlhR43O32X+TNpFyeQcPagPs2VwVR38xYUX44hnon54NHh137WXBJFabMdyxULDv3sDdVD2QmWetOU6JLSCwPJK8lycOtpVbAQaNYuQk7ka348EZWmmj3OGoPoAT5hrm47YjXm6KmCmk5LkFN3FbwEhQ4ATpjypC255CLNZQ8TlQUcUksAO60kZy6jC42vQywpGuTIFG/bnkzAzF24ERR44yBwTY4a7uoOEJFh/wBhkeAS8g6ufEAOBTRt4Jk7B/raAMSsd8NpjgAfuvGUGUJzLR5e4a2LCzsXSJSUXSj8c6A8l0U/3h/61GMPj90bOKOZuku4rFLrZhL81z/yTTku7ayOwp/tH7CaFlYeZCCZ0G73+jDQVO1vs6Ftga7h9mPZGZn41ZC/lNsLGXjHyn7y4/KU78ctQ+Da/ZFQsRkGhPkFXjhCfxj5L4gkjxcBQfhLdKar/8NuipmAFspqljghdF9rlJ4SRZ30TDGzB+NYNsl6OjuYdEBsehKZL+AEgc/47xDGSzT1zX2O1bcorn5+WrB4Y/FJCo=
  on:
    tags: true
    repo: Kasahs/freezer.js
